name: tea_select
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  circular_countdown_timer: ^0.2.0
  rflutter_alert: ^2.0.2
  firebase_auth: ^2.0.0
  provider: ^5.0.0
  cloud_firestore: ^2.2.0
  firebase_core: ^1.2.0
  image_picker: ^0.8.0+3
  firebase_storage: ^8.1.3
  shared_preferences: ^2.0.6
  flutter_ringtone_player: ^3.0.0
  flat_dialog: ^1.1.1
  flutter_launcher_icons: ^0.9.0
  esys_flutter_share: ^1.0.2
  path_provider: ^1.1.0
  google_mobile_ads: ^0.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/app image.jpg
    - images/logo_vertical.png
    - images/playstore.png

flutter_icons:
  android: true
  ios: true
  image_path: "images/playstore.png"